config:
  dockerfile: .woloxci/Dockerfile
  project_name: frontend-cookbook

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: "10"
      cache: "npm"
  - run: npm install
  - run: npm run lint

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
